USE [master]
GO
/****** Object:  Database [MobileHomeTracker]    Script Date: 3/23/2023 2:53:35 PM ******/
CREATE DATABASE [MobileHomeTracker]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MobileHomeTracker', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MobileHomeTracker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MobileHomeTracker_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MobileHomeTracker_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MobileHomeTracker] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MobileHomeTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MobileHomeTracker] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET ARITHABORT OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MobileHomeTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MobileHomeTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MobileHomeTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MobileHomeTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET RECOVERY FULL 
GO
ALTER DATABASE [MobileHomeTracker] SET  MULTI_USER 
GO
ALTER DATABASE [MobileHomeTracker] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MobileHomeTracker] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MobileHomeTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MobileHomeTracker] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MobileHomeTracker] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MobileHomeTracker] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MobileHomeTracker', N'ON'
GO
ALTER DATABASE [MobileHomeTracker] SET QUERY_STORE = OFF
GO
USE [MobileHomeTracker]
GO
/****** Object:  Table [dbo].[Home]    Script Date: 3/23/2023 2:53:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Home](
	[ID] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NULL,
 CONSTRAINT [PK_Homes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LocationRecord]    Script Date: 3/23/2023 2:53:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LocationRecord](
	[Longitude] [float] NOT NULL,
	[Latitude] [float] NOT NULL,
	[RecordDate] [datetime] NOT NULL,
	[ID] [uniqueidentifier] NOT NULL,
	[HomeID] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_LocationRecords] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LocationRecord]  WITH CHECK ADD  CONSTRAINT [FK_LocationRecords_Homes] FOREIGN KEY([HomeID])
REFERENCES [dbo].[Home] ([ID])
GO
ALTER TABLE [dbo].[LocationRecord] CHECK CONSTRAINT [FK_LocationRecords_Homes]
GO
USE [master]
GO
ALTER DATABASE [MobileHomeTracker] SET  READ_WRITE 
GO
